### ISSUE TITLE
load_dataset issue

### ISSUE THREAD

**Issue by SaranaAbidueva** [sag111/CEDR#1]
code lines from readme.md :

train_df = load_dataset('sagteam/cedr', name='enriched', split='train')
test_df = load_dataset('sagteam/cedr', name='enriched', split='test')

crash with FileNotFoundError.

This works fine:
train_df = load_dataset('cedr', name='enriched', split='train')
test_df = load_dataset('cedr', name='enriched', split='test')

**Comment by naumov-al** [comment]
You are right! This is a legacy from the local test version. 
Thanks a lot!
